name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-windows-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install speedtest-cli
          pip install pyinstaller

      - name: Build executable with PyInstaller (include speedtest)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install speedtest-cli
          pip install pyinstaller
          pyinstaller --onefile --windowed --hidden-import=speedtest --hidden-import=speedtest.cli --collect-submodules speedtest wifi_speed.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: wifi_speed_windows_exe
          path: dist/*.exe
